spring:
  application:
    name: AI-agent
  ai:
    dashscope:
      api-key: sk-49f8f7d585044c159b45eda51c5168be
      chat:
        options:
          model: qwen-flash-2025-07-28
          proxy-tool-calls: true
    vectorstore:
      type: in-memory
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
search-api:
  api-key: WWNKWMnJ8dhxMavAoNqqurpa
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.chenfuzhu.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
